server:
  port: 8081
spring:
  application:
    name: sc-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1/8081/eureka
    fetch-registry: false
    register-with-eureka: false
