spring:
  datasource:
    url: jdbc:mysql://${MARIADB_HOST:127.0.0.1}:3306/${MARIADB_NAME}?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: ${MARIADB_USERNAME:root}
    password: ${MARIADB_PASSWORD:root}
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    enabled: true
    baseline-version: 2.0
    baseline-on-migrate: false
    validate-on-migrate: true
    locations: classpath:db/mysql
    check-location: true
mybatis-plus:
  mapper-locations: classpath*:mapper/**/**.xml
  typeAliasesPackage: com.ruanzz
  global-config:
    db-config:
      id-type: auto
      field-strategy: 2
      column-underline: true
      capital-mode: true
      logic-delete-value: 1
      logic-not-delete-value: 0
    refresh: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    database-id: mysql

