server:
  port: 8090
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/sc
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
