---
- name: Register Ansible workdir
  shell: pwd |sed 's#roles/tls##'
  register: root_dir

- name: Create generate ssl dir
  file: dest={{ root_dir.stdout }}/ssl/{{ item }} state=directory
  with_items:
  - etcd
  - k8s

- name: Unarchive cfssl.tar.gz
  unarchive: src={{ software_dir }}/cfssl.tar.gz dest=/usr/bin/ mode=u+x

- name: Copy etcd ca config file
  template: src=etcd/{{ item }} dest={{ root_dir.stdout }}/ssl/etcd/{{ item.split('.')[:-1]|join('.') }}
  with_items:
  - ca-config.json.j2
  - ca-csr.json.j2
  - server-csr.json.j2

- name: Prepare gen etcd ca shell script
  copy: src=generate_etcd_cert.sh dest={{ root_dir.stdout }}/ssl/etcd mode=u+x

- name: Gen etcd cert file
  shell: cd {{ root_dir.stdout }}/ssl/etcd && /bin/bash generate_etcd_cert.sh

- name: Copy k8s ca config file
  template: src=k8s/{{ item }} dest={{ root_dir.stdout }}/ssl/k8s/{{ item.split('.')[:-1]|join('.') }}
  with_items:
  - ca-config.json.j2
  - ca-csr.json.j2
  - server-csr.json.j2
  - admin-csr.json.j2
  - kube-proxy-csr.json.j2

- name: Prepare k8s ca shell script
  copy: src=generate_k8s_cert.sh dest={{ root_dir.stdout }}/ssl/k8s mode=u+x

- name: Gen k8s cert file
  shell: cd {{ root_dir.stdout }}/ssl/k8s && /bin/bash generate_k8s_cert.sh
