---
- name: Stop firewalld
  service: name=firewalld state=stopped enabled=no

- name: Disable selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

- name: Diable swap
  lineinfile:
    dest: /etc/fstab
    regexp: ".*swap"
    line: ""

- name: Setenforce
  shell: setenforce 0 ; swapoff -a

- name: Copy timezone
  copy: src=/usr/share/zoneinfo/Asia/Shanghai dest=/etc/localtime

- name: Edit hosts
  template: src=hosts.j2 dest=/etc/hosts

